import Counter from "@/components/Counter";
import Descriptions from "@/components/Descriptions";
import Dog from "@/components/Dog";
import Parent from "@/components/Parent";
import Uncounter from "@/components/Uncounter";
import User from "@/components/User";
import Welcome from "@/components/Welcome";
import Head from "next/head";

export default function Home() {
  return (
    // fragment <> </> (fragmento pai que se incluem outros elementos)
    <> 
      <Head>
        <title>Fundamentos do React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Olá Mundo!</h1>
        {/* Comentário em JSX (ctrl+;) */}
        {/* Chamando o componente */}
        <Welcome />
        <User />
        {/* componente pai que possui componente filho incorporado */}
        <Parent />
        {/* Chamando o componente e chamando as props para o mesmo */}
        <Descriptions name="Afonso" age={18}/>
        {/* Desestruturação para passar props */}
        <Dog name="Rex" breed="Pitbull"/>
        {/* Contador */}
        <Counter />
        <Uncounter />
      </main>
    </>
  );
}
